# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ea50dc82b5b6bda6c765270bd8f6639802ceddd3ce8260d80291ba025c2990f63aedd9ca9a2548b4a8e3de64ffec92717a38f37266fdaf2f408fa04f1ffc4f7

test:
  secret_key_base: d5439416b59d6c52962355f83b913e3cc714a8d31d50f5598be381479c8def68ea3d75625d1ab6ea62a21dd46110aa206912ec3a3b4e801f4e3caf1fe3bd63d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
